ferncabrera/open_ims

client/.eslintrc.cjs
client/index.html
client/package-lock.json
client/package.json
client/src/App.tsx
client/src/globals.d.ts
client/src/utilities/apiCall.ts
client/src/utilities/apiHelpers.ts
client/src/utilities/types.ts
client/tsconfig.json
client/tsconfig.node.json
server/.gitignore
server/index.ts
server/package-lock.json
server/package.json
server/tsconfig.json

Bunch of configurations and skeleton things put in place to have the backend at least talk to the front end locally.
Great beginner examples of how to use Typescript and write Javascript in 5 hours when it could've taken less than 1.
(But we protect ourselves from errors and as this app gets bigger, it's much easier to scale)
npm install both in server and client folders.
npm run dev in server
npm run dev in client
to test any changes run `npm run build` in either or.

create server and connect to front-end

---

server/index.ts
server/package-lock.json
server/package.json

We should have logging for all API calls made to our server (otherwise how do we know it is being hit LOL)

Adding logging to our server

---

client/Dockerfile.dev
client/src/App.tsx
client/src/utilities/apiHelpers.ts
client/vite.config.ts
k8s/client-cluster-ip-service.yaml
k8s/client-deployment.yaml
k8s/ingress-service.yaml
k8s/server-cluster-ip-service.yaml
k8s/server-deployment.yaml
server/Dockerfile.dev
server/index.ts
skaffold.yaml

Can now start the dev env with one command!
skaffold dev --no-prune=false --cache-artifacts=false

Docker +Skaffold + K8s configuration

---

client/src/App.tsx
server/Dockerfile.dev

testing beep fixing docker

---

common/database/pgadmin/.env
common/database/pgadmin/kustomization.yaml
common/database/pgadmin/pgadmin-config.yaml
common/database/pgadmin/pgadmin-persistent-volume-claim.yaml
common/database/pgadmin/pgadmin-secret.yaml
common/database/pgadmin/pgadmin-service.yaml
common/database/pgadmin/pgadmin-statefuls-set.yaml
common/ingress/base/ingress-service.yaml
microservices/server/db/index.ts
microservices/server/index.ts
skaffold.yaml

Got sidetracked looking into postgres best practices for production and ended up refactoring our example to follow the examples outline in the node-postgres docs as well as included a PgAdmin4 server that now runs in a container that can be accessed using localhost:30007. In this case port needs to be specified as I have exposed it explicilty as we cannot really "load balance" requests to PgAdmin4.
To use this PSQL editor tool simply launch the app as normal, and you may have to **wait** a little. It takes some time to setup the PgAdmin4 server so going to localhost:30007 may not load anything for a minute or two. You can confirm it is running by checking the logs for the container in Docker Desktop similar to how you connect to the DB, in this case click on the container named …

implemented node 'pg' package best practice; implemented pgadmin4

---

microservices/server/index.ts
microservices/server/src/controllers/open_ims.ts
microservices/server/src/controllers/test.ts
microservices/server/src/db/helpers/index.ts
microservices/server/src/db/index.ts
microservices/server/src/db/queries/index.ts
microservices/server/src/routes/initialize/index.ts
microservices/server/src/routes/open_ims.ts
microservices/server/src/routes/test.ts
microservices/server/src/routes/users.ts
microservices/server/src/utils/catchAsync.ts

Set up our file structure for our express application for our back-end.
Thank-you to @ferncabrera for helping out with the db structure folder.
Structure goes as follows:
Our main folder is the source folder. It contains and holds a better structured set of sub folders within it:
- **controllers**: Operations that happen in a given route. Your typical request and response objects operating within an api call.
- **db**: index contains our seed operations. All other subfolders are reusable query functions that can be used throughout the app. Same pool is exported and reused from index so we don't create accidental overhead.
- **middleware**: Empty for now, but can be used to protect our api routes with auth in the future as well as define other custom middleware.
- **routes**: contains our …

Backend Architecture Implementation

---

.gitignore
microservices/client/.eslintrc.cjs
microservices/client/package-lock.json
microservices/client/package.json
microservices/client/src/components/forms/Password.module.scss
microservices/client/src/components/forms/Password.tsx
microservices/client/src/components/modals/CenteredModal.tsx
microservices/client/src/containers/auth/Login/index.tsx
microservices/client/src/containers/auth/Register/index.tsx
microservices/client/src/containers/auth/index.module.scss
microservices/client/src/containers/auth/index.tsx
microservices/client/src/containers/auth/tests/Login.test.tsx
microservices/client/src/containers/auth/tests/Register.test.tsx
microservices/client/src/containers/auth/tests/__snapshots__/Login.test.tsx.snap
microservices/client/src/containers/auth/tests/__snapshots__/Register.test.tsx.snap
microservices/client/src/globals.d.ts
microservices/client/src/main.tsx
microservices/client/src/styles/forms.scss
microservices/client/src/styles/general/colors.scss
microservices/client/src/utilities/apiCall.ts
microservices/client/src/utilities/apiHelpers.ts
microservices/client/src/utilities/types/types.ts
microservices/client/src/utilities/types/validationTypes.ts
microservices/client/src/utilities/validation.ts
microservices/client/tests/setup.js
microservices/client/tsconfig.json
microservices/client/vite.config.ts

Completed Validations on the front-end for registration and login pages.
This is where things can get iffy, and since I haven't had testing implemented yet, I would like to ask both @ferncabrera and @kellygibson to try and break this.
Check the console.log to make sure no post request is going through unless every field is validated. Also let's make sure everyone is happy with the fields. They don't entirely match the mockups on figma, but that is due to bootstrap icon placement, and simplifying a field to just be listed as required. So it's especially important @kellygibson reviews this. 
Do not merge until all approvals are present. 
Also, still need to add email validation to the reset password request field.

Registration and Login Front End Validations

---

skaffold.yaml

re-trying deployment

---

microservices/client/src/components/forms/Password.tsx
microservices/client/src/containers/auth/Login/index.module.scss
microservices/client/src/containers/auth/Login/index.tsx
microservices/client/src/containers/auth/Register/index.module.scss
microservices/client/src/containers/auth/Register/index.tsx
microservices/client/src/containers/auth/index.module.scss
microservices/client/src/containers/auth/tests/__snapshots__/Login.test.tsx.snap
microservices/client/src/containers/auth/tests/__snapshots__/Register.test.tsx.snap
microservices/client/src/styles/forms.scss
microservices/client/src/styles/general/variables.scss

- Fixed spacing margins on screens.
- Prepend round alert icon in validation text through css if there is a validation error.
- Updated text for password requirements validation.
- Switched eye icon for password to Md icon (thanks for finding it Kelly).
- Improved accessibility by making all forms support keyboard submission.

Form Field Fixes

---

common/database/kustomize/overlays/dev/postgres-credentials.yaml
microservices/client/src/containers/auth/Login/index.tsx
microservices/client/src/containers/auth/Register/index.tsx
microservices/client/src/utilities/apiCall.ts
microservices/client/src/utilities/apiHelpers.ts
microservices/client/src/utilities/types/types.ts
microservices/server/index.ts
microservices/server/kustomize/base/server-deployment.yaml
microservices/server/kustomize/overlays/dev/.env
microservices/server/kustomize/overlays/dev/postgres-credentials-patch.json
microservices/server/kustomize/overlays/prod/.env
microservices/server/kustomize/overlays/prod/postgres-credentials-patch.json
microservices/server/package-lock.json
microservices/server/package.json
microservices/server/src/controllers/open_ims.ts
microservices/server/src/controllers/test.ts
microservices/server/src/controllers/users.ts
microservices/server/src/db/schema.ts
microservices/server/src/middleware/errorHandler.ts
microservices/server/src/routes/initialize/index.ts
microservices/server/src/routes/users.ts
microservices/server/src/utils/customError.ts

Registration creates user in the database.
Login verifies user email and password from database. Basic back-end error handling.
Cookie is created upon successful login.
---
Need a separate ticket for creating front-end loading state.
Redux for success global message banners (need reusable component as well)
Need more cases for error handling in the back-end and reflecting it to the front-end incase something goes wrong.
--- 
Ready to merge.
Please review all operations in Network tab and PGadmin. I will come home tonight, and if there are no questions I can merge it myself. (Or fernando/kelly/joseph can).

Backend authentication

---

common/utils/migration-job/kustomize/base/migration-job.yaml

Brought PROD down using cluster-context from my local, this is to reset our credentials on the server.

PROD RESET

---

common/utils/migration-job/index.js
common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-up.sql

This PR just finalizes some err msgs for your DB migrations during dev.

finalizing local db development

---

common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-up.sql

investiagting if tables are really dropped

---

common/utils/migration-job/database.json
common/utils/migration-job/index.js
common/utils/migration-job/kustomize/overlays/dev/.env
common/utils/migration-job/kustomize/overlays/prod/.env
common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-down.sql
common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-up.sql
common/utils/migration-job/package.json

fixing misc issues found while @kellygibson was working on importing DB tables to our migration script.

updating migration job to avoid ghost down-migrations

---

.gitignore
Linux.md
common/utils/migration-job/Dockerfile
common/utils/migration-job/Dockerfile.migrations
microservices/server/Dockerfile
microservices/server/Dockerfile.dev

So the current implementation makes it possible for me to run this all on linux.
I don't know exactly what every line does, I sort of gave it a shotgun blast method where I am alternating between root user and node user (for permissions) as well as giving the chown command to grant permissions for node users to change certain files and directories.
There are some sources that say this is not a secure method of handling things, but I think we could be a little lenient for operations sake. 
@ferncabrera if you could check and make sure that with these changes, you are still able to fluidly run skaffold dev, I think we are good to merge these changes. Let me know.
Also, the changes in Dockerfile.migrations, and .dev may not be necessary. I am not sure, I will double check. Keeping this …

dockerfile changes

---

microservices/server/src/controllers/forgot_pass.ts

Just changed the url from localhost to the production url.

using production url for forgot password

---

microservices/client/src/components/mainComponents/Sidebar.tsx
microservices/client/src/containers/auth/Login/index.tsx
microservices/client/src/containers/auth/index.tsx
microservices/client/src/containers/main/MainContainer.tsx
microservices/client/src/routes.tsx
microservices/client/src/utilities/helpers/functions.ts
microservices/client/tsconfig.json
microservices/client/tsconfig.node.json
microservices/server/package-lock.json
microservices/server/src/controllers/users.ts
microservices/server/src/routes/users.ts
microservices/server/tsconfig.json

Basic authentication routes added for when a user signs in.
User signing in - cannot access login or register page
User not signed in - won't be able to access ccg inventory
Cookie data (first name, email, and permission ) is passed from back-end to front-end when requested. Can potentially store in global state.

basic authentication added

---

microservices/client/src/containers/auth/ResetPass/index.module.scss
microservices/client/src/containers/auth/ResetPass/index.tsx
microservices/client/src/routes.tsx
microservices/client/src/utilities/apiHelpers.ts
microservices/server/src/controllers/forgot_pass.ts
microservices/server/src/routes/forgot_pass.ts

- Reset password URL changed from query string to dynamic URL.
- Encoded token via Base64 instead of uriComponentEncoding
- Forgot password route protected (you need the email with a valid token link in order to access it)
- Verified all update and password check options work
- User IS able to use the same valid url multiple times. This is OK for now, may need to be changed in the future.
- Removed body scss styling, main page and css styles are fixed.
(Use BREVO api's that @JosephFanous sent on discord in local .secret.env file to test functionality)

updated reset password

---

microservices/server/index.ts
microservices/server/jest.config.js
microservices/server/middleware/errorHandler.ts
microservices/server/package-lock.json
microservices/server/package.json
microservices/server/src/controllers/forgot_pass.ts
microservices/server/src/controllers/tests/forgot_pass.test.ts
microservices/server/src/controllers/tests/open_ims.test.ts
microservices/server/src/controllers/tests/users.test.ts
microservices/server/src/controllers/users.ts
microservices/server/src/globals.d.ts

Implemented JEST back-end unit tests for all our controller functions.
Please look at the current test implementations to get an idea of how the formatting works as well as the mocking.

Back testing

---

common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-down.sql
common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-up.sql

Updating Migration

---

microservices/client/src/containers/auth/ResetPass/index.tsx

had to change a 201 status code to a 200.

fix password not updating on reset

---

microservices/client/package-lock.json
microservices/client/package.json
microservices/client/src/atoms/state.ts
microservices/client/src/components/banners/GlobalBanner.tsx
microservices/client/src/components/banners/index.module.scss
microservices/client/src/containers/auth/Login/index.tsx
microservices/client/src/containers/auth/Register/index.tsx
microservices/client/src/containers/auth/index.tsx
microservices/client/src/containers/auth/tests/Login.test.tsx
microservices/client/src/containers/auth/tests/Register.test.tsx
microservices/client/src/containers/auth/tests/__snapshots__/Login.test.tsx.snap
microservices/client/src/globals.d.ts
microservices/client/src/main.tsx
microservices/client/src/styles/general/colors.scss
microservices/server/src/controllers/users.ts

Global banners are now supported. PM me for details or look at file changes for a better understanding.

recoil implementation

---

README.md
common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-down.sql
common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-up.sql
scripts/create-secrets-and-config-map.sh
start.sh

Some small modifications to ensure the database does not have Update/Delete/Insert anomalies.
No adjustments to the actual dashboard though, those will be included in the next PR.

DB normalization, re-org, and admin user creation

---

microservices/server/src/controllers/customers.ts

fixed by placing in ILIKE query instead of LIKE in sql.

make search case insesnsitive

---

microservices/client/src/atoms/state.ts
microservices/client/src/components/table/TableLink.tsx
microservices/client/src/containers/customers/DefaultCustomers.tsx
microservices/client/src/containers/customers/TableSchema.tsx
microservices/client/src/containers/operationController/OperationController.tsx
microservices/client/src/containers/operationController/RenderEdit.tsx
microservices/client/src/containers/operationController/RenderNew.tsx
microservices/client/src/containers/operationController/RenderRead.tsx
microservices/client/src/globals.d.ts
microservices/client/src/main.tsx
microservices/client/src/routes.tsx

we have controller support now.
Each form we make whether it's for editing, reading, or creating can now be imported into one of the render methods that come from that controller. No need to worry about react routing and clogging the schema routes file.

crud controller implementation

---

common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-up.sql
microservices/client/src/components/calendars/CCGDateRangePicker.module.scss
microservices/client/src/components/cards/SimpleSummaryCard.module.scss
microservices/client/src/components/cards/SimpleSummaryCard.tsx
microservices/client/src/components/charts/CCGChart.tsx
microservices/client/src/components/mainComponents/Sidebar.tsx
microservices/client/src/components/mainComponents/sidebar.module.scss
microservices/client/src/containers/dashboard/AdminDashboard.tsx
microservices/client/src/containers/main/index.module.scss
microservices/client/src/styles/general/colors.scss
microservices/client/src/styles/general/mixins.scss

Lots of styling for the dashboard, and handling logic required to display previous metric data.

57 create dashboardlanding page

---

microservices/client/src/components/cards/SimpleSummaryCard.tsx
microservices/client/src/components/charts/CCGChart.tsx
microservices/client/src/containers/dashboard/AdminDashboard.tsx

Misc changes
Still thinking about how to best show the data - for now will work on implementing a global state banner to help display some of the information regarding the dashboard in the future perhaps.....

Styling changes to text; min fontsize set

---

microservices/client/src/components/forms/CrudForm.tsx
microservices/client/src/containers/auth/Login/index.tsx
microservices/client/src/containers/auth/Register/index.tsx
microservices/client/src/containers/auth/tests/__snapshots__/Login.test.tsx.snap
microservices/client/src/containers/auth/tests/__snapshots__/Register.test.tsx.snap
microservices/client/src/containers/customers/EditCustomer.tsx
microservices/client/src/styles/forms.scss
microservices/server/src/controllers/customers.ts

Added form validations for the customer edit page.
Includes front-end validations on:
- Company Name,
- First Name,
- Last Name,
- Email,
- Phone
~Will work on backend as well while I am at it, do not merge.~
Backend validations also in place. Can be tested via postman.
https://speeding-eclipse-693541.postman.co/workspace/open_ims~26614a76-665a-4e6f-9016-a4f8221debc7/request/14052476-d32daf1c-df03-4fc2-a995-75f90f713884
Let me know if you need access.

Customer Edit (Frontend and Backend Validations)

---

microservices/client/src/components/table/CCGTable.tsx
microservices/client/src/containers/customers/EditCustomer.tsx
microservices/client/src/containers/customers/ReadCustomer.tsx
microservices/client/src/containers/customers/ReadTableSchema.tsx
microservices/client/src/containers/customers/TableSchema.tsx
microservices/client/src/containers/main/index.module.scss
microservices/client/src/containers/operationController/OperationController.tsx
microservices/client/src/containers/operationController/RenderRead.tsx
microservices/client/src/globals.d.ts
microservices/client/src/styles/general/index.scss
microservices/server/src/controllers/invoices.ts
microservices/server/src/middleware/errorHandler.ts
microservices/server/src/routes/initialize/index.ts
microservices/server/src/routes/invoices.ts

Made the read screen
**SEARCH FILTER DOES NOT SUPPORT DATE SEARCH** 
It's a little more complicated with ISO strings and how it may be searched for in the database. @ferncabrera had some experience with the charts for querying dates from the DB, so maybe he can open a separate issue and visit this :)
----
There need to be many database changes, but to go forward with the project I made this PR. Multiple issues will be opened.
Please review to ensure that functionality and styling work ok.

Customer read

---

microservices/client/src/atoms/state.ts
microservices/client/src/components/buttons/PillButton.tsx
microservices/client/src/components/forms/CrudForm.module.scss
microservices/client/src/components/forms/CrudForm.tsx
microservices/client/src/containers/customers/DefaultCustomers.tsx
microservices/client/src/containers/customers/EditCustomer.tsx
microservices/client/src/containers/customers/ReadCustomer.tsx
microservices/client/src/containers/main/MainContainer.tsx
microservices/client/src/containers/operationController/OperationController.tsx
microservices/client/src/styles/buttons.scss

Added pillboxes and breadcrumbs.
Buttons are not operational yet, need separate issues/tickets for them. They do presently exist however.

CRUD Pillboxes & Breadcrumbs

---

microservices/client/src/components/buttons/PillButton.tsx
microservices/client/src/components/table/CCGTable.tsx
microservices/client/src/containers/auth/Login/index.tsx
microservices/client/src/containers/customers/DefaultCustomers.tsx
microservices/client/src/containers/customers/ReadCustomer.tsx
microservices/client/src/containers/main/MainContainer.tsx
microservices/client/src/utilities/apiHelpers.ts
microservices/server/src/controllers/customers.ts
microservices/server/src/routes/customers.ts

Delete works 100% fluidly with the customer page.

Delete Functionality Customer Page

---

common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-up.sql
microservices/client/src/containers/customers/EditCustomer.tsx
microservices/client/src/containers/customers/ReadCustomer.tsx
microservices/server/src/controllers/customers.ts

Added shipping and billing to customers. 
Updated the data base as well.

add shipping and billing names to customers

---

microservices/client/src/containers/customers/DefaultCustomers.tsx
microservices/client/src/containers/customers/EditCreateCustomer.tsx
microservices/client/src/containers/customers/ReadCustomer.tsx

update front-end error handling

---

microservices/client/src/components/buttons/filters/InputFilter.tsx
microservices/client/src/components/table/CCGTable.tsx
microservices/client/src/containers/customers/ReadCustomer.tsx
microservices/client/src/containers/invoices/DefaultInvoices.tsx
microservices/server/src/controllers/invoices.ts

Using mcdonald's wifi to merge this into main.

Filter input

---

microservices/client/src/components/graphics/StatusPill.module.scss
microservices/client/src/components/table/CCGTable.tsx
microservices/client/src/containers/customers/DefaultCustomers.tsx
microservices/client/src/containers/employees/DefaultEmployees.tsx
microservices/client/src/containers/invoices/DefaultInvoices.tsx
microservices/client/src/containers/purchaseOrders/DefaultPurchaseOrders.tsx
microservices/client/src/containers/purchaseOrders/TableSchema.tsx
microservices/client/src/containers/users/DefaultUsers.tsx
microservices/client/src/containers/users/TableSchema.tsx
microservices/client/src/containers/vendors/DefaultVendors.tsx
microservices/server/src/controllers/customers.ts
microservices/server/src/controllers/purchase_orders.ts
microservices/server/src/controllers/users.ts
microservices/server/src/controllers/vendors.ts
microservices/server/src/middleware/errorHandler.ts

Each commit has its own enhancement, feature, or bug fix. 
Due to working totally offline, I could not create separate issues or branches at the time.
Good news is that I have found eduroam wifi connection at the Unveristy of Stuttgart here in Germany. So I can pretty much just walk into the library and work here lol.

Some fixes here and there - Dev Oliver

---

microservices/client/src/containers/customers/DefaultCustomers.tsx
microservices/client/src/containers/customers/ReadCustomer.tsx
microservices/client/src/containers/employees/DefaultEmployees.tsx
microservices/client/src/containers/invoices/DefaultInvoices.tsx
microservices/client/src/containers/purchaseOrders/DefaultPurchaseOrders.tsx
microservices/client/src/containers/users/DefaultUsers.tsx
microservices/client/src/containers/vendors/DefaultVendors.tsx

Hey Fernando. Merge this whenever you are ready :)
This is to address the style changes you requested from this isse: https://github.com/ferncabrera/open_ims/issues/192
Let me know if this is good by merging. Otherwise, leave a comment and I will address again as soon as I have wifi.
Once this is done and merged, I will work on the other crud screens.

Style change views

---

common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-up.sql
microservices/client/src/components/forms/CrudForm.tsx
microservices/client/src/components/table/CCGTable.tsx
microservices/client/src/containers/customers/EditCreateCustomer.tsx
microservices/client/src/containers/customers/ReadCustomer.tsx
microservices/client/src/containers/customers/ReadTableSchema.tsx
microservices/client/src/containers/invoices/EditCreateInvoice.tsx
microservices/client/src/containers/invoices/ProductTableSchema.tsx
microservices/client/src/containers/invoices/ReadInvoice.tsx
microservices/client/src/containers/invoices/TableSchema.tsx
microservices/client/src/containers/operationController/RenderEdit.tsx
microservices/client/src/containers/operationController/RenderNew.tsx
microservices/client/src/containers/operationController/RenderRead.tsx
microservices/client/src/containers/vendors/DefaultVendors.tsx
microservices/client/src/containers/vendors/EditCreateVendor.tsx
microservices/client/src/containers/vendors/ReadVendor.tsx
microservices/client/src/containers/vendors/VendorPurchaseTableSchema.tsx
microservices/client/src/utilities/helpers/functions.ts
microservices/client/src/utilities/validation.ts
microservices/server/package-lock.json
microservices/server/src/controllers/customers.ts
microservices/server/src/controllers/invoices.ts
microservices/server/src/controllers/purchase_orders.ts
microservices/server/src/controllers/vendors.ts
microservices/server/src/routes/customers.ts
microservices/server/src/routes/invoices.ts
microservices/server/src/routes/purchase_orders.ts
microservices/server/src/routes/vendors.ts

Includes all CRUD operations for Vendors screens and tables.

Vendors crud

---

common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-up.sql
microservices/client/src/components/forms/CrudForm.tsx
microservices/client/src/components/table/CCGTable.tsx
microservices/client/src/containers/customers/DefaultCustomers.tsx
microservices/client/src/containers/customers/ReadCustomer.tsx
microservices/client/src/containers/employees/DefaultEmployees.tsx
microservices/client/src/containers/invoices/DefaultInvoices.tsx
microservices/client/src/containers/invoices/EditCreateInvoice.tsx
microservices/client/src/containers/invoices/ProductTableSchema.tsx
microservices/client/src/containers/invoices/ReadInvoice.tsx
microservices/client/src/containers/invoices/TableSchema.tsx
microservices/client/src/containers/operationController/RenderEdit.tsx
microservices/client/src/containers/operationController/RenderNew.tsx
microservices/client/src/containers/operationController/RenderRead.tsx
microservices/client/src/containers/purchaseOrders/DefaultPurchaseOrders.tsx
microservices/client/src/containers/users/DefaultUsers.tsx
microservices/client/src/containers/vendors/DefaultVendors.tsx
microservices/client/src/utilities/helpers/functions.ts
microservices/server/src/controllers/invoices.ts
microservices/server/src/controllers/purchase_orders.ts
microservices/server/src/routes/invoices.ts
microservices/server/src/routes/purchase_orders.ts

Blocked due to uncertainty of invoice structure and incomplete DB of products table.
@ferncabrera Critical, please address as soon as possible.

Invoices CRUD

---

common/grafana/kustomize/overlays/dev/Test-1.json
common/grafana/kustomize/overlays/prod/Test-1.json
common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-up.sql
microservices/client/.env.development
microservices/client/Dockerfile.staging
microservices/client/package.json
microservices/client/src/components/calendars/CCGDateRangePicker.tsx
microservices/client/src/containers/dashboard/AdminDashboard.tsx
microservices/client/src/containers/operationController/OperationController.tsx
microservices/client/src/utilities/helpers/functions.ts
microservices/client/src/utilities/types/types.ts

still literally everything todo security-wise..... but at least for now we have a standardized way to display any business metric data using an embedded Grafana dashboard and our DB as the datasource.
Will continue to work on this as we address more critical DB architecture/design issues as we've spoken about @Polsander .

Dashboarding first implementation/POC w/ Grafana finalized

---

.github/workflows/pr_merge.yaml

No need fix
